name: JMeter Test ub docker

on:
  workflow_dispatch:
  
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  performance_test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 8  # Adjust to your Java version

      - name: Download and Install JMeter
        run: |
          wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xf apache-jmeter-5.4.1.tgz
          rm apache-jmeter-5.4.1.tgz

      - name: Set up Docker
        uses: docker/build-push-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-jmeter-image .
      
      - name: Run JMeter test in Docker
        run: |
          docker run --rm -v $PWD:/tests my-jmeter-image \
          ./apache-jmeter-5.4.1/bin/jmeter -J-Xms2g -J-Xmx16g -n -t test.jmx
